#!/bin/bash

# Loop 16 times
# for i in {1..8}
# do
#    echo "Iteration $i"
#    # Place your commands here
#    python phc/run_hydra.py learning=im_mcp_big  exp_name=phc_comp_3 \
# env=env_im_getup_mcp robot=smpl_humanoid env.zero_out_far=False \
# robot.real_weight_porpotion_boxes=False env.num_prim=3 \
# env.motion_file=./data/amass/pkls/amass_isaac_im_train_take6_upright_slim.pkl \
# env.models=['output/HumanoidIm/phc_3/Humanoid.pth'] env.num_envs=1024 \
# headless=True epoch=-1 test=True im_eval=True \
# collect_dataset=True  \
# env.add_action_noise=True \
# env.mlp_bypass=False \
# env.action_noise_std=0.05 \
# env.start_idx=0
# done

# python phc/run_hydra.py learning=im_mcp_big  exp_name=phc_comp_3 \
# env=env_im_getup_mcp robot=smpl_humanoid env.zero_out_far=False \
# robot.real_weight_porpotion_boxes=False env.num_prim=3 \
# env.motion_file=./data/amass/pkls/amass_isaac_im_train_take6_upright_slim.pkl \
# env.models=['output/HumanoidIm/phc_3/Humanoid.pth'] env.num_envs=1 \
# headless=True epoch=-1 test=True env.mlp_bypass=True 

CUDA_VISIBLE_DEVICES=2 python phc/run_hydra.py learning=im_mcp_big  exp_name=phc_comp_3 env=env_im_getup_mcp robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/xinpeng/PHC_xinpeng/data/amass/pkls/amass_isaac_im_train_take6_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=768 headless=True epoch=-1 test=True im_eval=True collect_dataset=True  env.add_action_noise=True  env.action_noise_std=0.10
CUDA_VISIBLE_DEVICES=2 python phc/run_hydra.py learning=im_mcp_big  exp_name=phc_comp_3 env=env_im_getup_mcp robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/xinpeng/PHC_xinpeng/data/amass/pkls/amass_isaac_im_train_take6_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=768 headless=True epoch=-1 test=True im_eval=True collect_dataset=True  env.add_action_noise=True  env.action_noise_std=0.15
CUDA_VISIBLE_DEVICES=2 python phc/run_hydra.py learning=im_mcp_big  exp_name=phc_comp_3 env=env_im_getup_mcp robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/xinpeng/PHC_xinpeng/data/amass/pkls/amass_isaac_im_train_take6_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=768 headless=True epoch=-1 test=True im_eval=True collect_dataset=True  env.add_action_noise=True  env.action_noise_std=0.20
CUDA_VISIBLE_DEVICES=2 python phc/run_hydra.py learning=im_mcp_big  exp_name=phc_comp_3 env=env_im_getup_mcp robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/xinpeng/PHC_xinpeng/data/amass/pkls/amass_isaac_im_train_take6_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=768 headless=True epoch=-1 test=True im_eval=True collect_dataset=True  env.add_action_noise=True  env.action_noise_std=0.25
CUDA_VISIBLE_DEVICES=2 python phc/run_hydra.py learning=im_mcp_big  exp_name=phc_comp_3 env=env_im_getup_mcp robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/xinpeng/PHC_xinpeng/data/amass/pkls/amass_isaac_im_train_take6_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=768 headless=True epoch=-1 test=True im_eval=True collect_dataset=True  env.add_action_noise=True  env.action_noise_std=0.30
CUDA_VISIBLE_DEVICES=2 python phc/run_hydra.py learning=im_mcp_big  exp_name=phc_comp_3 env=env_im_getup_mcp robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/xinpeng/PHC_xinpeng/data/amass/pkls/amass_isaac_im_train_take6_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=768 headless=True epoch=-1 test=True im_eval=True collect_dataset=True  env.add_action_noise=True  env.action_noise_std=0.35
CUDA_VISIBLE_DEVICES=2 python phc/run_hydra.py learning=im_mcp_big  exp_name=phc_comp_3 env=env_im_getup_mcp robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/xinpeng/PHC_xinpeng/data/amass/pkls/amass_isaac_im_train_take6_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=768 headless=True epoch=-1 test=True im_eval=True collect_dataset=True  env.add_action_noise=True  env.action_noise_std=0.40
CUDA_VISIBLE_DEVICES=2 python phc/run_hydra.py learning=im_mcp_big  exp_name=phc_comp_3 env=env_im_getup_mcp robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/xinpeng/PHC_xinpeng/data/amass/pkls/amass_isaac_im_train_take6_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=768 headless=True epoch=-1 test=True im_eval=True collect_dataset=True  env.add_action_noise=True  env.action_noise_std=0.45
CUDA_VISIBLE_DEVICES=2 python phc/run_hydra.py learning=im_mcp_big  exp_name=phc_comp_3 env=env_im_getup_mcp robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/xinpeng/PHC_xinpeng/data/amass/pkls/amass_isaac_im_train_take6_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=768 headless=True epoch=-1 test=True im_eval=True collect_dataset=True  env.add_action_noise=True  env.action_noise_std=0.50
CUDA_VISIBLE_DEVICES=2 python phc/run_hydra.py learning=im_mcp_big  exp_name=phc_comp_3 env=env_im_getup_mcp robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/xinpeng/PHC_xinpeng/data/amass/pkls/amass_isaac_im_train_take6_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=768 headless=True epoch=-1 test=True im_eval=True collect_dataset=True  env.add_action_noise=True  env.action_noise_std=0.55
CUDA_VISIBLE_DEVICES=2 python phc/run_hydra.py learning=im_mcp_big  exp_name=phc_comp_3 env=env_im_getup_mcp robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/xinpeng/PHC_xinpeng/data/amass/pkls/amass_isaac_im_train_take6_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=768 headless=True epoch=-1 test=True im_eval=True collect_dataset=True  env.add_action_noise=True  env.action_noise_std=0.60
CUDA_VISIBLE_DEVICES=2 python phc/run_hydra.py learning=im_mcp_big  exp_name=phc_comp_3 env=env_im_getup_mcp robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/xinpeng/PHC_xinpeng/data/amass/pkls/amass_isaac_im_train_take6_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=768 headless=True epoch=-1 test=True im_eval=True collect_dataset=True  env.add_action_noise=True  env.action_noise_std=0.65
CUDA_VISIBLE_DEVICES=2 python phc/run_hydra.py learning=im_mcp_big  exp_name=phc_comp_3 env=env_im_getup_mcp robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/xinpeng/PHC_xinpeng/data/amass/pkls/amass_isaac_im_train_take6_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=768 headless=True epoch=-1 test=True im_eval=True collect_dataset=True  env.add_action_noise=True  env.action_noise_std=0.70
CUDA_VISIBLE_DEVICES=2 python phc/run_hydra.py learning=im_mcp_big  exp_name=phc_comp_3 env=env_im_getup_mcp robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/xinpeng/PHC_xinpeng/data/amass/pkls/amass_isaac_im_train_take6_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=768 headless=True epoch=-1 test=True im_eval=True collect_dataset=True  env.add_action_noise=True  env.action_noise_std=0.75

# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=1 env.reaction_mode=momentum env.external_interference_amplitude=0
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=1 env.reaction_mode=momentum env.external_interference_amplitude=30
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=1 env.reaction_mode=momentum env.external_interference_amplitude=60
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=1 env.reaction_mode=momentum env.external_interference_amplitude=90
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=1 env.reaction_mode=momentum env.external_interference_amplitude=120
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=1 env.reaction_mode=momentum env.external_interference_amplitude=150
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=1 env.reaction_mode=momentum env.external_interference_amplitude=180
# 
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=2 env.reaction_mode=momentum env.external_interference_amplitude=30
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=2 env.reaction_mode=momentum env.external_interference_amplitude=60
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=2 env.reaction_mode=momentum env.external_interference_amplitude=90
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=2 env.reaction_mode=momentum env.external_interference_amplitude=120
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=2 env.reaction_mode=momentum env.external_interference_amplitude=150
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=2 env.reaction_mode=momentum env.external_interference_amplitude=180
# 
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=3 env.reaction_mode=momentum env.external_interference_amplitude=30
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=3 env.reaction_mode=momentum env.external_interference_amplitude=60
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=3 env.reaction_mode=momentum env.external_interference_amplitude=90
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=3 env.reaction_mode=momentum env.external_interference_amplitude=120
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=3 env.reaction_mode=momentum env.external_interference_amplitude=150
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=3 env.reaction_mode=momentum env.external_interference_amplitude=180
# 
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=4 env.reaction_mode=momentum env.external_interference_amplitude=30
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=4 env.reaction_mode=momentum env.external_interference_amplitude=60
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=4 env.reaction_mode=momentum env.external_interference_amplitude=90
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=4 env.reaction_mode=momentum env.external_interference_amplitude=120
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=4 env.reaction_mode=momentum env.external_interference_amplitude=150
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=4 env.reaction_mode=momentum env.external_interference_amplitude=180
# 
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=5 env.reaction_mode=momentum env.external_interference_amplitude=30
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=5 env.reaction_mode=momentum env.external_interference_amplitude=60
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=5 env.reaction_mode=momentum env.external_interference_amplitude=90
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=5 env.reaction_mode=momentum env.external_interference_amplitude=120
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=5 env.reaction_mode=momentum env.external_interference_amplitude=150
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=5 env.reaction_mode=momentum env.external_interference_amplitude=180
# 
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=6 env.reaction_mode=momentum env.external_interference_amplitude=30
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=6 env.reaction_mode=momentum env.external_interference_amplitude=60
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=6 env.reaction_mode=momentum env.external_interference_amplitude=90
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=6 env.reaction_mode=momentum env.external_interference_amplitude=120
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=6 env.reaction_mode=momentum env.external_interference_amplitude=150
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=6 env.reaction_mode=momentum env.external_interference_amplitude=180
# 
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=7 env.reaction_mode=momentum env.external_interference_amplitude=30
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=7 env.reaction_mode=momentum env.external_interference_amplitude=60
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=7 env.reaction_mode=momentum env.external_interference_amplitude=90
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=7 env.reaction_mode=momentum env.external_interference_amplitude=120
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=7 env.reaction_mode=momentum env.external_interference_amplitude=150
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=7 env.reaction_mode=momentum env.external_interference_amplitude=180
# 
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=8 env.reaction_mode=momentum env.external_interference_amplitude=30
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=8 env.reaction_mode=momentum env.external_interference_amplitude=60
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=8 env.reaction_mode=momentum env.external_interference_amplitude=90
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=8 env.reaction_mode=momentum env.external_interference_amplitude=120
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=8 env.reaction_mode=momentum env.external_interference_amplitude=150
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=8 env.reaction_mode=momentum env.external_interference_amplitude=180
# 
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=9 env.reaction_mode=momentum env.external_interference_amplitude=30
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=9 env.reaction_mode=momentum env.external_interference_amplitude=60
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=9 env.reaction_mode=momentum env.external_interference_amplitude=90
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=9 env.reaction_mode=momentum env.external_interference_amplitude=120
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=9 env.reaction_mode=momentum env.external_interference_amplitude=150
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=9 env.reaction_mode=momentum env.external_interference_amplitude=180
# 
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=10 env.reaction_mode=momentum env.external_interference_amplitude=30
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=10 env.reaction_mode=momentum env.external_interference_amplitude=60
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=10 env.reaction_mode=momentum env.external_interference_amplitude=90
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=10 env.reaction_mode=momentum env.external_interference_amplitude=120
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=10 env.reaction_mode=momentum env.external_interference_amplitude=150
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=10 env.reaction_mode=momentum env.external_interference_amplitude=180
# 
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=11 env.reaction_mode=momentum env.external_interference_amplitude=30
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=11 env.reaction_mode=momentum env.external_interference_amplitude=60
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=11 env.reaction_mode=momentum env.external_interference_amplitude=90
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=11 env.reaction_mode=momentum env.external_interference_amplitude=120
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=11 env.reaction_mode=momentum env.external_interference_amplitude=150
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=11 env.reaction_mode=momentum env.external_interference_amplitude=180
# 
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=12 env.reaction_mode=momentum env.external_interference_amplitude=30
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=12 env.reaction_mode=momentum env.external_interference_amplitude=60
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=12 env.reaction_mode=momentum env.external_interference_amplitude=90
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=12 env.reaction_mode=momentum env.external_interference_amplitude=120
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=12 env.reaction_mode=momentum env.external_interference_amplitude=150
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=12 env.reaction_mode=momentum env.external_interference_amplitude=180
# 
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=13 env.reaction_mode=momentum env.external_interference_amplitude=30
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=13 env.reaction_mode=momentum env.external_interference_amplitude=60
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=13 env.reaction_mode=momentum env.external_interference_amplitude=90
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=13 env.reaction_mode=momentum env.external_interference_amplitude=120
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=13 env.reaction_mode=momentum env.external_interference_amplitude=150
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=13 env.reaction_mode=momentum env.external_interference_amplitude=180
# 
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=14 env.reaction_mode=momentum env.external_interference_amplitude=30
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=14 env.reaction_mode=momentum env.external_interference_amplitude=60
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=14 env.reaction_mode=momentum env.external_interference_amplitude=90
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=14 env.reaction_mode=momentum env.external_interference_amplitude=120
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=14 env.reaction_mode=momentum env.external_interference_amplitude=150
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=14 env.reaction_mode=momentum env.external_interference_amplitude=180
# 
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=15 env.reaction_mode=momentum env.external_interference_amplitude=30
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=15 env.reaction_mode=momentum env.external_interference_amplitude=60
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=15 env.reaction_mode=momentum env.external_interference_amplitude=90
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=15 env.reaction_mode=momentum env.external_interference_amplitude=120
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=15 env.reaction_mode=momentum env.external_interference_amplitude=150
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=15 env.reaction_mode=momentum env.external_interference_amplitude=180
# 
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=16 env.reaction_mode=momentum env.external_interference_amplitude=30
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=16 env.reaction_mode=momentum env.external_interference_amplitude=60
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=16 env.reaction_mode=momentum env.external_interference_amplitude=90
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=16 env.reaction_mode=momentum env.external_interference_amplitude=120
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=16 env.reaction_mode=momentum env.external_interference_amplitude=150
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=16 env.reaction_mode=momentum env.external_interference_amplitude=180
# 
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=17 env.reaction_mode=momentum env.external_interference_amplitude=30
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=17 env.reaction_mode=momentum env.external_interference_amplitude=60
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=17 env.reaction_mode=momentum env.external_interference_amplitude=90
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=17 env.reaction_mode=momentum env.external_interference_amplitude=120
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=17 env.reaction_mode=momentum env.external_interference_amplitude=150
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=17 env.reaction_mode=momentum env.external_interference_amplitude=180
# 
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=18 env.reaction_mode=momentum env.external_interference_amplitude=30
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=18 env.reaction_mode=momentum env.external_interference_amplitude=60
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=18 env.reaction_mode=momentum env.external_interference_amplitude=90
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=18 env.reaction_mode=momentum env.external_interference_amplitude=120
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=18 env.reaction_mode=momentum env.external_interference_amplitude=150
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=18 env.reaction_mode=momentum env.external_interference_amplitude=180
# 
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=19 env.reaction_mode=momentum env.external_interference_amplitude=30
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=19 env.reaction_mode=momentum env.external_interference_amplitude=60
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=19 env.reaction_mode=momentum env.external_interference_amplitude=90
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=19 env.reaction_mode=momentum env.external_interference_amplitude=120
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=19 env.reaction_mode=momentum env.external_interference_amplitude=150
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=19 env.reaction_mode=momentum env.external_interference_amplitude=180
# 
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=20 env.reaction_mode=momentum env.external_interference_amplitude=30
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=20 env.reaction_mode=momentum env.external_interference_amplitude=60
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=20 env.reaction_mode=momentum env.external_interference_amplitude=90
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=20 env.reaction_mode=momentum env.external_interference_amplitude=120
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=20 env.reaction_mode=momentum env.external_interference_amplitude=150
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=20 env.reaction_mode=momentum env.external_interference_amplitude=180
# 
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=21 env.reaction_mode=momentum env.external_interference_amplitude=30
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=21 env.reaction_mode=momentum env.external_interference_amplitude=60
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=21 env.reaction_mode=momentum env.external_interference_amplitude=90
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=21 env.reaction_mode=momentum env.external_interference_amplitude=120
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=21 env.reaction_mode=momentum env.external_interference_amplitude=150
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=21 env.reaction_mode=momentum env.external_interference_amplitude=180
# 
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=22 env.reaction_mode=momentum env.external_interference_amplitude=30
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=22 env.reaction_mode=momentum env.external_interference_amplitude=60
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=22 env.reaction_mode=momentum env.external_interference_amplitude=90
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=22 env.reaction_mode=momentum env.external_interference_amplitude=120
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=22 env.reaction_mode=momentum env.external_interference_amplitude=150
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=22 env.reaction_mode=momentum env.external_interference_amplitude=180
# 
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=23 env.reaction_mode=momentum env.external_interference_amplitude=30
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=23 env.reaction_mode=momentum env.external_interference_amplitude=60
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=23 env.reaction_mode=momentum env.external_interference_amplitude=90
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=23 env.reaction_mode=momentum env.external_interference_amplitude=120
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=23 env.reaction_mode=momentum env.external_interference_amplitude=150
# CUDA_VISIBLE_DEVICES=7 python phc/run_hydra.py learning=im_mcp_big exp_name=phc_comp_3 env=env_im_getup_mcp_reaction robot=smpl_humanoid env.zero_out_far=False robot.real_weight_porpotion_boxes=False env.num_prim=3 env.motion_file=/hdd/caizixuan/PULSE/sample_data/amass_isaac_simple_run_upright_slim.pkl env.models=\['output/HumanoidIm/phc_3/Humanoid.pth'\] env.num_envs=256 headless=True epoch=-1 test=True im_eval=True collect_dataset=True env.reaction_idx=23 env.reaction_mode=momentum env.external_interference_amplitude=180
